[http]
address = "127.0.0.1:8000"
allowed_origins = [".*"] # RegexSet

[database]
url = "postgres://academy@127.0.0.1:5432/academy" # https://docs.rs/tokio-postgres/latest/tokio_postgres/config/struct.Config.html

[cache]
url = "redis://127.0.0.1:6379/0" # https://docs.rs/redis/latest/redis/#connection-parameters

[email]
smtp_url = "smtp://academy:academy@127.0.0.1:2525" # https://docs.rs/lettre/latest/lettre/transport/smtp/struct.AsyncSmtpTransport.html#method.from_url
from = "Bootstrap Academy DEV <dev@bootstrap.academy>"

[jwt]
secret = "changeme"

[internal]
shop_url = "http://127.0.0.1:8004/shop/"

[session]
access_token_ttl = "1d"

[contact]
email = "Contact <contact@example.com>"

[recaptcha]
enable = false
siteverify_endpoint_override = "http://127.0.0.1:8001/recaptcha/api/siteverify"
sitekey = "test-sitekey"
secret = "test-secret"

[vat]
validate_endpoint_override = "http://127.0.0.1:8003/validate/"

[oauth2.providers.test]
enable = true
name = "Test"
client_id = "client-id"
client_secret = "client-secret"
auth_url = "http://127.0.0.1:8002/oauth2/authorize"
token_url = "http://127.0.0.1:8002/oauth2/token"
userinfo_url = "http://127.0.0.1:8002/user"
userinfo_id_key = "id"
userinfo_name_key = "name"
scopes = []

[oauth2.providers.github]
enable = false
client_id = ""
client_secret = ""

[oauth2.providers.discord]
enable = false
client_id = ""
client_secret = ""

[oauth2.providers.google]
enable = false
client_id = ""
client_secret = ""
