name: build

on:
  push:
    branches: [develop]
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'push' && github.actor == 'github-merge-queue[bot]') }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v15
        with:
          name: academy-backend
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: false
      - run: nix build -L --keep-going
      - run: nix build -L --keep-going .#testing
      - run: nix build -L --keep-going .#devShell
      - run: nix build -L --keep-going .#tests.composite
